name: Lint

on:
  pull_request:
    branches:
      - main
      - 'releases/**'
    paths:
      - 'apps/web/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        run: npm install # Will fix it with ci , but for now install will work 

      - name: Run ESLint
        run: npm run lint
